all:
  children:
    provisioner_servers:
      hosts:
        provisioner-server:
          ansible_host: "134.209.16.223"
          ansible_user: root
          # Persistent SSH host keys - no need for StrictHostKeyChecking=no

          # Configuration from Terraform outputs
          server_name: provisioner.comcar.net
          server_region: lon1
          provisioner_version: "latest"
          github_repo: "carmendata-workshop/provisioner"
          auto_start_service: true
          server_timezone: "UTC"

      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pipelining: true
        provisioner_install_dir: "/opt/provisioner"
        provisioner_config_dir: "/etc/provisioner"
        provisioner_state_dir: "/var/lib/provisioner"
        provisioner_log_dir: "/var/log/provisioner"
        provisioner_user: "provisioner"
        provisioner_service: "provisioner"
