name: Manual Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      force_release:
        description: 'Force release even if version already exists'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

jobs:
  call-auto-release:
    name: Call Auto Release Workflow
    uses: ./.github/workflows/auto-release.yml
    with:
      version: ${{ github.ref_name || inputs.version }}
      force_release: ${{ inputs.force_release || false }}
    permissions:
      contents: write
      actions: read